version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      firebase:
        dependency-type: "production"
        patterns:
          - "firebase-*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
